### ISSUE TITLE
DriveTrain: remove max macro and M_PI definition

### ISSUE THREAD

**Issue by calcmogul** [frc3512/Robot-2015#2]
The max macro is unused. Even if it were, std::max in the algorithm header should be used instead. Also, M_PI is defined properly in the cmath header on Linux, so we don't need to define it ourselves.

**Comment by RogShotz** [comment]
Is this still an issue, we should review this, and if not remove it from the issue box.

**Comment by calcmogul** [comment]
It most definitely is still an issue. I put these here as simple bugs for students to fix themselves.

**Comment by RogShotz** [comment]
Closed
